// Browser-side MSW worker. Not wired into the app or any spec yet - see the module doc in
// ./handlers.ts. Requires the service worker script at public/mockServiceWorker.js (generated by
// `msw init public --save`, already committed) to be served from the app's origin before
// `worker.start()` is called.
import { setupWorker } from "msw/browser";
import { handlers } from "./handlers";

export const worker = setupWorker(...handlers);
